FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir grpcio grpcio-tools

COPY . .

# Generate gRPC
RUN python -m grpc_tools.protoc -I./proto --python_out=./gen --grpc_python_out=./gen ./proto/scheduler.proto ./proto/telemetry.proto ./proto/raft.proto

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

CMD ["python", "services/basestation-sim/client.py"]
